Repository dcbhupendra7/Computer-Architecture, pull requests merged in 2024-11, with the labels that each got.

#2 added load and store code on cache simulator
  .gitignore
  __pycache__/cache.cpython-312.pyc
  cache.py
  main.py
  memory_trace.txt
Labels: Development

#3 Add initial implementation of cache simulator with LOAD/STORE handling
  __pycache__/cache.cpython-312.pyc
  __pycache__/cli_parser.cpython-312.pyc
  cache.py
  memory_trace.txt
Labels: Development

#5 Add Cache Statistics
  cache.py
  main.py
Labels: Development

#6 Updated Statistics
  cache.py
Labels: Development

#7 final report in statitcs and completion message in main
  cache.py
  main.py
Labels: Development

#8 GUI implemented
  gui.py
Labels: Development

#9 update gui with differnet modes
  gui.py
Labels: bug

#10 add reset button to reset the values
  gui.py
Labels: Development

#11 fix: change button implementation independently
  gui.py
Labels: bug, enhancement

#12 fix: UI Improvements
  gui.py
Labels: bug

#13 Add flowchart
  Flowchart.pdf
  cache.py
  gui.py
Labels: bug
